name: ci
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
permissions: {}
defaults:
  run:
    shell: bash -euo pipefail {0}
jobs:
  build:
    runs-on: macos-26
    env:
      DEVELOPER_DIR: /Applications/Xcode_26.0.1.app
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae  # v5.0.5
        with:
          path: |
            ~/Library/Caches/org.swift.swiftpm
            ~/Library/org.swift.swiftpm
            ~/.swiftpm
            .build
          key: ${{ runner.os }}-swiftpm-${{ hashFiles('Package.resolved') }}
          restore-keys: ${{ runner.os }}-swiftpm-
      - run: echo "SWIFT=$(xcrun -f swift)" >> "$GITHUB_ENV"
      - run: |
          "$SWIFT" --version
      - run: |
          "$SWIFT" build --sdk "$(xcrun --sdk iphoneos --show-sdk-path)" --triple arm64-apple-ios --explicit-target-dependency-import-check error
  lint:
    runs-on: ubuntu-24.04-arm
    container: swift:6.2
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - run: swift format lint -rsp .
  yamllint:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - run: yamllint --version
      - run: yamllint --strict --config-file .yamllint.yml .
